package com.map.retirement.repository;

import com.map.retirement.model.RetirementReport;
import com.map.retirement.model.RetirementReport.ReportStatus;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Repository for RetirementReport persistence.
 * Story: MAP-20 — Retirement Readiness Report Generation
 * Epic:  MAP-5  — Retirement Planning Tools
 */
@Repository
public interface RetirementReportRepository extends JpaRepository<RetirementReport, Long> {

    /** Find all reports for a specific client */
    List<RetirementReport> findByClientIdOrderByCreatedAtDesc(Long clientId);

    /** Find all reports generated by a specific advisor */
    List<RetirementReport> findByAdvisorIdOrderByCreatedAtDesc(Long advisorId);

    /** Find reports by status */
    List<RetirementReport> findByStatus(ReportStatus status);

    /** Find reports by advisor and client */
    List<RetirementReport> findByAdvisorIdAndClientId(Long advisorId, Long clientId);
}
