package com.elitea.tests.goals;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Automated API tests for MAP-12 — As a client, I want to set my financial goals,
 * so that my portfolio strategy is properly aligned.
 *
 * Confluence spec: https://duggisrinivasarao.atlassian.net/wiki/spaces/~557058465a0e4979f9409ab37f2f57376baf82/pages/13172738/MAP-12+Test+Specification+Research
 * Jira story:      https://duggisrinivasarao.atlassian.net/browse/MAP-12
 * Generated by:    Claude (Elitea Test Automation Pipeline)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class FinancialGoalTest {

    private static final String BASE_URL = System.getProperty(
        "api.base.url", "https://api.edwardjones-map.com"
    );
    private static final String AUTH_TOKEN = System.getProperty(
        "api.auth.token", ""
    );

    private static String createdGoalId;

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    // ──────────────────────────────────────────────────────────────────────────
    // AC1: Given a client is in their profile,
    //      When they access the goals section,
    //      Then they can select from predefined goal types
    //      (retirement, education, wealth growth) and add custom ones.
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    @Order(1)
    @DisplayName("AC1: Client can create a goal with a predefined goal type (RETIREMENT)")
    void test_createGoal_withPredefinedType_returns201() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "RETIREMENT");
        requestBody.put("goalName", "Retire at 65");
        requestBody.put("targetAmount", 1500000.00);
        requestBody.put("targetDate", "2045-06-30");
        requestBody.put("priorityLevel", 1);

        Response response = given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(201)
            .body("goalId", notNullValue())
            .body("goalType", equalTo("RETIREMENT"))
            .body("goalName", equalTo("Retire at 65"))
            .body("targetAmount", equalTo(1500000.00f))
            .body("targetDate", equalTo("2045-06-30"))
            .body("priorityLevel", equalTo(1))
            .body("status", notNullValue())
        .extract().response();

        createdGoalId = response.jsonPath().getString("goalId");
        assertNotNull(createdGoalId, "goalId must be returned on successful creation");
    }

    @Test
    @Order(2)
    @DisplayName("AC1: Client can create a goal with EDUCATION_SAVINGS goal type")
    void test_createGoal_withEducationSavingsType_returns201() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "EDUCATION_SAVINGS");
        requestBody.put("goalName", "College Fund for Child");
        requestBody.put("targetAmount", 120000.00);
        requestBody.put("targetDate", "2035-09-01");
        requestBody.put("priorityLevel", 2);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(201)
            .body("goalId", notNullValue())
            .body("goalType", equalTo("EDUCATION_SAVINGS"))
            .body("goalName", equalTo("College Fund for Child"));
    }

    @Test
    @Order(3)
    @DisplayName("AC1: Client can create a goal with WEALTH_GROWTH goal type")
    void test_createGoal_withWealthGrowthType_returns201() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "WEALTH_GROWTH");
        requestBody.put("goalName", "Double Net Worth");
        requestBody.put("targetAmount", 500000.00);
        requestBody.put("targetDate", "2032-12-31");
        requestBody.put("priorityLevel", 3);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(201)
            .body("goalId", notNullValue())
            .body("goalType", equalTo("WEALTH_GROWTH"));
    }

    @Test
    @Order(4)
    @DisplayName("AC1: Creating a goal with an invalid goalType returns 422")
    void test_createGoal_withInvalidGoalType_returns422() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "INVALID_TYPE");
        requestBody.put("goalName", "Bad Goal");
        requestBody.put("targetAmount", 50000.00);
        requestBody.put("targetDate", "2030-01-01");
        requestBody.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(422)
            .body("message", notNullValue());
    }

    @Test
    @Order(5)
    @DisplayName("AC1: Creating a goal without auth token returns 401")
    void test_createGoal_returns401_withoutToken() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "RETIREMENT");
        requestBody.put("goalName", "Unauthorized Goal");
        requestBody.put("targetAmount", 100000.00);
        requestBody.put("targetDate", "2040-01-01");
        requestBody.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer ")
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(401);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // AC2: Given a client sets a goal with a target amount and date,
    //      When they save it,
    //      Then the goal is visible to their financial advisor on the advisor dashboard.
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    @Order(6)
    @DisplayName("AC2: Created goal is retrievable and visible with correct target amount and date")
    void test_createGoal_thenGetGoals_goalVisibleWithCorrectFields() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "HOME_PURCHASE");
        requestBody.put("goalName", "Buy a Home");
        requestBody.put("targetAmount", 350000.00);
        requestBody.put("targetDate", "2028-06-15");
        requestBody.put("priorityLevel", 2);

        String newGoalId = given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(201)
            .body("goalId", notNullValue())
        .extract().jsonPath().getString("goalId");

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
        .when()
            .get("/goals")
        .then()
            .statusCode(200)
            .body("goalId", hasItem(newGoalId))
            .body("find { it.goalId == '" + newGoalId + "' }.goalType", equalTo("HOME_PURCHASE"))
            .body("find { it.goalId == '" + newGoalId + "' }.targetAmount", equalTo(350000.00f))
            .body("find { it.goalId == '" + newGoalId + "' }.targetDate", equalTo("2028-06-15"));
    }

    @Test
    @Order(7)
    @DisplayName("AC2: Creating a goal with a past targetDate returns 422")
    void test_createGoal_withPastTargetDate_returns422() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "EMERGENCY_FUND");
        requestBody.put("goalName", "Past Date Goal");
        requestBody.put("targetAmount", 20000.00);
        requestBody.put("targetDate", "2020-01-01");
        requestBody.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(422)
            .body("message", notNullValue());
    }

    @Test
    @Order(8)
    @DisplayName("AC2: Creating a goal with a negative targetAmount returns 422")
    void test_createGoal_withNegativeTargetAmount_returns422() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "WEALTH_GROWTH");
        requestBody.put("goalName", "Negative Amount Goal");
        requestBody.put("targetAmount", -5000.00);
        requestBody.put("targetDate", "2035-01-01");
        requestBody.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(422)
            .body("message", notNullValue());
    }

    @Test
    @Order(9)
    @DisplayName("AC2: Exceeding 5 active goals limit returns 409")
    void test_createGoal_whenMaxGoalsExceeded_returns409() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "EMERGENCY_FUND");
        requestBody.put("goalName", "Sixth Goal — Should Be Rejected");
        requestBody.put("targetAmount", 10000.00);
        requestBody.put("targetDate", "2030-12-31");
        requestBody.put("priorityLevel", 5);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .post("/goals")
        .then()
            .statusCode(409)
            .body("message", containsString("maximum"));
    }

    // ──────────────────────────────────────────────────────────────────────────
    // AC3: Given a client wants to update goals,
    //      When they edit and save,
    //      Then the updated goals are reflected immediately without data loss.
    // ──────────────────────────────────────────────────────────────────────────

    @Test
    @Order(10)
    @DisplayName("AC3: Updating a goal reflects new values immediately without data loss")
    void test_updateGoal_reflectsNewValues_returns200() {
        assertNotNull(createdGoalId, "Prerequisite: goal must have been created in AC1 test @Order(1)");

        Map<String, Object> updatedBody = new HashMap<>();
        updatedBody.put("goalType", "RETIREMENT");
        updatedBody.put("goalName", "Retire at 62 — Updated");
        updatedBody.put("targetAmount", 2000000.00);
        updatedBody.put("targetDate", "2042-03-31");
        updatedBody.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(updatedBody)
        .when()
            .put("/goals/" + createdGoalId)
        .then()
            .statusCode(200)
            .body("goalId", equalTo(createdGoalId))
            .body("goalName", equalTo("Retire at 62 — Updated"))
            .body("targetAmount", equalTo(2000000.00f))
            .body("targetDate", equalTo("2042-03-31"))
            .body("priorityLevel", equalTo(1))
            .body("goalType", equalTo("RETIREMENT"));
    }

    @Test
    @Order(11)
    @DisplayName("AC3: Updating a goal with a past targetDate returns 422 and does not corrupt data")
    void test_updateGoal_withPastDate_returns422_noDataLoss() {
        assertNotNull(createdGoalId, "Prerequisite: goal must have been created in AC1 test @Order(1)");

        Map<String, Object> invalidUpdate = new HashMap<>();
        invalidUpdate.put("goalType", "RETIREMENT");
        invalidUpdate.put("goalName", "Retire at 62 — Updated");
        invalidUpdate.put("targetAmount", 2000000.00);
        invalidUpdate.put("targetDate", "2019-01-01");
        invalidUpdate.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(invalidUpdate)
        .when()
            .put("/goals/" + createdGoalId)
        .then()
            .statusCode(422)
            .body("message", notNullValue());

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
        .when()
            .get("/goals")
        .then()
            .statusCode(200)
            .body("find { it.goalId == '" + createdGoalId + "' }.targetDate", equalTo("2042-03-31"));
    }

    @Test
    @Order(12)
    @DisplayName("AC3: Updating a non-existent goal returns 404")
    void test_updateGoal_returns404_whenGoalNotExists() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "RETIREMENT");
        requestBody.put("goalName", "Ghost Goal");
        requestBody.put("targetAmount", 100000.00);
        requestBody.put("targetDate", "2040-01-01");
        requestBody.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .put("/goals/non-existent-goal-id-00000")
        .then()
            .statusCode(404)
            .body("message", notNullValue());
    }

    @Test
    @Order(13)
    @DisplayName("AC3: Updating a goal without auth token returns 401")
    void test_updateGoal_returns401_withoutToken() {
        assertNotNull(createdGoalId, "Prerequisite: goal must have been created in AC1 test @Order(1)");

        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("goalType", "RETIREMENT");
        requestBody.put("goalName", "Unauthorized Update");
        requestBody.put("targetAmount", 999999.00);
        requestBody.put("targetDate", "2040-01-01");
        requestBody.put("priorityLevel", 1);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer ")
            .body(requestBody)
        .when()
            .put("/goals/" + createdGoalId)
        .then()
            .statusCode(401);
    }
}
