package com.elitea.tests.advisor;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import java.util.List;
import java.util.Map;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Automated API tests for MAP-16 — Advisor Consolidated Client Portfolio View
 * Confluence spec: https://duggisrinivasarao.atlassian.net/wiki/spaces/~557058465a0e4979f9409ab37f2f57376baf82/pages/17137667
 * Jira story:      https://duggisrinivasarao.atlassian.net/browse/MAP-16
 * Generated by:    Claude (Elitea Test Automation Pipeline)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class AdvisorDashboardTest {

    private static final String BASE_URL = System.getProperty("api.base.url", "https://api.edwardjones-map.com");
    private static final String ADVISOR_TOKEN = System.getProperty("api.advisor.token", "");
    private static final String CLIENT_TOKEN = System.getProperty("api.client.token", "");
    private static final String VALID_CLIENT_ID = System.getProperty("test.valid.client.id", "550e8400-e29b-41d4-a716-446655440000");
    private static final String NONEXISTENT_CLIENT_ID = System.getProperty("test.nonexistent.client.id", "00000000-0000-0000-0000-000000000000");
    private static final String MALFORMED_CLIENT_ID = "not-a-valid-uuid-format";

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test @Order(1)
    @DisplayName("AC1 TC-01: GET /advisor/dashboard returns 200 with all client summary fields")
    void test_advisor_dashboard_returns_200_with_client_list() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(200)
            .body("clients", notNullValue())
            .body("clients[0].clientId", notNullValue())
            .body("clients[0].portfolioValue", notNullValue())
            .body("clients[0].dailyChangePct", notNullValue())
            .body("clients[0].riskLevel", notNullValue())
            .body("clients[0].highlightFlag", notNullValue())
            .body("clients[0].portfolioLink", notNullValue());
    }

    @Test @Order(2)
    @DisplayName("AC1 TC-02: GET /advisor/dashboard returns 401 without Authorization header")
    void test_advisor_dashboard_returns_401_without_token() {
        given().contentType(ContentType.JSON)
        .when().get("/advisor/dashboard")
        .then().statusCode(401);
    }

    @Test @Order(3)
    @DisplayName("AC1 TC-03: GET /advisor/dashboard returns 401 with invalid JWT")
    void test_advisor_dashboard_returns_401_with_invalid_token() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer invalid.jwt.token")
        .when().get("/advisor/dashboard")
        .then().statusCode(401);
    }

    @Test @Order(4)
    @DisplayName("AC1 TC-04: GET /advisor/dashboard returns 403 for CLIENT role")
    void test_advisor_dashboard_returns_403_for_client_role() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + CLIENT_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(403);
    }

    @Test @Order(5)
    @DisplayName("AC1 TC-05: GET /advisor/dashboard returns 200 with empty clients list when advisor has no clients")
    void test_advisor_dashboard_returns_200_with_empty_list() {
        String emptyAdvisorToken = System.getProperty("api.empty.advisor.token", ADVISOR_TOKEN);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + emptyAdvisorToken)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("clients", notNullValue());
    }

    @Test @Order(6)
    @DisplayName("AC2 TC-06: Sort by portfolioValue ascending returns low to high order")
    void test_advisor_dashboard_sort_by_portfolio_value_ascending() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("sortBy", "portfolioValue").queryParam("order", "asc")
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("clients", notNullValue()).extract().response();
        List<Float> values = r.jsonPath().getList("clients.portfolioValue");
        if (values != null && values.size() > 1) {
            for (int i = 0; i < values.size() - 1; i++)
                assertTrue(values.get(i) <= values.get(i + 1), "Not sorted ascending at index " + i);
        }
    }

    @Test @Order(7)
    @DisplayName("AC2 TC-07: Sort by performance descending returns high to low order")
    void test_advisor_dashboard_sort_by_performance_descending() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("sortBy", "performance").queryParam("order", "desc")
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("clients", notNullValue()).extract().response();
        List<Float> values = r.jsonPath().getList("clients.dailyChangePct");
        if (values != null && values.size() > 1) {
            for (int i = 0; i < values.size() - 1; i++)
                assertTrue(values.get(i) >= values.get(i + 1), "Not sorted descending at index " + i);
        }
    }

    @Test @Order(8)
    @DisplayName("AC2 TC-08: Filter by riskLevel=HIGH returns only HIGH risk clients")
    void test_advisor_dashboard_filter_by_risk_level_high() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("filterBy", "riskLevel").queryParam("value", "HIGH")
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("clients", notNullValue()).extract().response();
        List<String> levels = r.jsonPath().getList("clients.riskLevel");
        if (levels != null) for (String level : levels) assertEquals("HIGH", level);
    }

    @Test @Order(9)
    @DisplayName("AC2 TC-09: Sort by lastContactDate ascending returns oldest contact first")
    void test_advisor_dashboard_sort_by_last_contact_date_ascending() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("sortBy", "lastContactDate").queryParam("order", "asc")
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("clients", notNullValue());
    }

    @Test @Order(10)
    @DisplayName("AC2 TC-10: Invalid sortBy parameter returns 400")
    void test_advisor_dashboard_returns_400_with_invalid_sort_param() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("sortBy", "unknownField")
        .when().get("/advisor/dashboard")
        .then().statusCode(400);
    }

    @Test @Order(11)
    @DisplayName("AC3 TC-11: Client with dailyChangePct < -5% has highlightFlag=true")
    void test_highlight_flag_true_for_loss_exceeding_threshold() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).extract().response();
        List<Float> pcts = r.jsonPath().getList("clients.dailyChangePct");
        List<Boolean> flags = r.jsonPath().getList("clients.highlightFlag");
        if (pcts != null && flags != null)
            for (int i = 0; i < pcts.size(); i++)
                if (pcts.get(i) < -5.0f) assertTrue(flags.get(i), "highlightFlag must be true when pct=" + pcts.get(i));
    }

    @Test @Order(12)
    @DisplayName("AC3 TC-12: Client at boundary dailyChangePct=-5% has highlightFlag=false (exclusive)")
    void test_highlight_flag_false_at_boundary() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).extract().response();
        List<Float> pcts = r.jsonPath().getList("clients.dailyChangePct");
        List<Boolean> flags = r.jsonPath().getList("clients.highlightFlag");
        if (pcts != null && flags != null)
            for (int i = 0; i < pcts.size(); i++)
                if (pcts.get(i) == -5.0f) assertFalse(flags.get(i), "highlightFlag must be false at -5% boundary");
    }

    @Test @Order(13)
    @DisplayName("AC3 TC-13: Client with dailyChangePct > -5% has highlightFlag=false")
    void test_highlight_flag_false_for_normal_performance() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).extract().response();
        List<Float> pcts = r.jsonPath().getList("clients.dailyChangePct");
        List<Boolean> flags = r.jsonPath().getList("clients.highlightFlag");
        if (pcts != null && flags != null)
            for (int i = 0; i < pcts.size(); i++)
                if (pcts.get(i) > -5.0f) assertFalse(flags.get(i), "highlightFlag must be false when pct=" + pcts.get(i));
    }

    @Test @Order(14)
    @DisplayName("AC3 TC-14: Highlighted clients (highlightFlag=true) appear before non-highlighted clients")
    void test_highlighted_clients_appear_first() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).extract().response();
        List<Boolean> flags = r.jsonPath().getList("clients.highlightFlag");
        if (flags != null && flags.size() > 1) {
            boolean seenFalse = false;
            for (Boolean flag : flags) {
                if (flag != null && !flag) seenFalse = true;
                if (seenFalse && flag != null && flag) fail("Highlighted client found after non-highlighted client");
            }
        }
    }

    @Test @Order(15)
    @DisplayName("AC4 TC-15: Every client in dashboard has a non-null portfolioLink")
    void test_all_clients_have_portfolio_link() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("clients.portfolioLink", everyItem(notNullValue()));
    }

    @Test @Order(16)
    @DisplayName("AC4 TC-16: GET /portfolio/{clientId} returns 200 with full portfolio detail")
    void test_portfolio_detail_returns_200_for_valid_client() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/portfolio/{clientId}", VALID_CLIENT_ID)
        .then().statusCode(200)
            .body("totalPortfolioValue", notNullValue())
            .body("dailyChange", notNullValue())
            .body("holdings", notNullValue());
    }

    @Test @Order(17)
    @DisplayName("AC4 TC-17: GET /portfolio/{clientId} returns 404 for non-existent client")
    void test_portfolio_detail_returns_404_for_nonexistent_client() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/portfolio/{clientId}", NONEXISTENT_CLIENT_ID)
        .then().statusCode(404);
    }

    @Test @Order(18)
    @DisplayName("AC4 TC-18: GET /portfolio/{clientId} returns 400 for malformed clientId")
    void test_portfolio_detail_returns_400_for_malformed_id() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/portfolio/{clientId}", MALFORMED_CLIENT_ID)
        .then().statusCode(400);
    }

    @Test @Order(19)
    @DisplayName("AC5 TC-19: GET /advisor/dashboard includes pagination metadata")
    void test_dashboard_includes_pagination_metadata() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
        .when().get("/advisor/dashboard")
        .then().statusCode(200)
            .body("page", notNullValue()).body("pageSize", notNullValue())
            .body("totalCount", notNullValue()).body("totalPages", notNullValue());
    }

    @Test @Order(20)
    @DisplayName("AC5 TC-20: GET /advisor/dashboard?page=2&pageSize=20 returns page 2 of results")
    void test_dashboard_pagination_page_2() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("page", 2).queryParam("pageSize", 20)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("page", equalTo(2)).body("pageSize", equalTo(20));
    }

    @Test @Order(21)
    @DisplayName("AC5 TC-21: GET /advisor/dashboard?pageSize=50 returns at most 50 clients")
    void test_dashboard_pagination_large_page_size() {
        Response r = given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("page", 1).queryParam("pageSize", 50)
        .when().get("/advisor/dashboard")
        .then().statusCode(200).body("pageSize", equalTo(50)).extract().response();
        List<?> clients = r.jsonPath().getList("clients");
        assertNotNull(clients);
        assertTrue(clients.size() <= 50);
    }

    @Test @Order(22)
    @DisplayName("AC5 TC-22: GET /advisor/dashboard?page=999 returns 200 empty or 404 for out-of-range page")
    void test_dashboard_pagination_out_of_range_page() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("page", 999).queryParam("pageSize", 20)
        .when().get("/advisor/dashboard")
        .then().statusCode(anyOf(equalTo(200), equalTo(404)));
    }

    @Test @Order(23)
    @DisplayName("AC5 TC-23: GET /advisor/dashboard?pageSize=0 returns 400 for invalid page size")
    void test_dashboard_pagination_returns_400_for_zero_page_size() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .queryParam("page", 1).queryParam("pageSize", 0)
        .when().get("/advisor/dashboard")
        .then().statusCode(400);
    }
}
