package com.elitea.tests.advisor;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Automated API tests for MAP-25 — Flag Client Account for Priority Review
 * Confluence spec: https://duggisrinivasarao.atlassian.net/wiki/spaces/~557058465a0e4979f9409ab37f2f57376baf82/pages/13172760/MAP-25+Test+Specification+Research
 * Generated by: Claude (Elitea Test Automation Pipeline)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class PriorityFlagTest {

    private static final String BASE_URL = System.getProperty(
        "api.base.url", "https://api.edwardjones-map.com"
    );
    private static final String AUTH_TOKEN = System.getProperty(
        "api.auth.token", ""
    );
    private static final String CLIENT_ID = System.getProperty(
        "test.client.id", "client-uuid-001"
    );
    private static final String NON_EXISTENT_CLIENT_ID = "non-existent-client-99999";

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    @Order(1)
    @DisplayName("AC1: Flag account for priority review returns 200 with flagged=true")
    void test_flag_client_account_returns_200_with_valid_payload() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("flagged", true);
        requestBody.put("reason", "PORTFOLIO_CONCERN");
        requestBody.put("reasonNote", "Client portfolio shows significant risk exposure.");

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .put("/clients/" + CLIENT_ID + "/flag")
        .then()
            .statusCode(200)
            .body("clientId", equalTo(CLIENT_ID))
            .body("flagged", equalTo(true))
            .body("reason", equalTo("PORTFOLIO_CONCERN"))
            .body("flaggedAt", notNullValue())
            .body("flaggedBy", notNullValue());
    }

    @Test
    @Order(2)
    @DisplayName("AC1: Flagged account appears at top of advisor dashboard flagged list")
    void test_flagged_account_appears_at_top_of_dashboard() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
        .when()
            .get("/advisor/dashboard/flagged")
        .then()
            .statusCode(200)
            .body("$", not(empty()))
            .body("[0].clientId", notNullValue())
            .body("[0].reason", notNullValue())
            .body("[0].flaggedAt", notNullValue());
    }

    @Test
    @Order(3)
    @DisplayName("AC2: Add reason note to flagged account and verify note is saved")
    void test_flag_account_with_reason_note_saves_note_in_response() {
        String reasonNote = "Life event detected — client recently retired. Portfolio rebalancing required.";
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("flagged", true);
        requestBody.put("reason", "LIFE_EVENT");
        requestBody.put("reasonNote", reasonNote);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .put("/clients/" + CLIENT_ID + "/flag")
        .then()
            .statusCode(200)
            .body("flagged", equalTo(true))
            .body("reason", equalTo("LIFE_EVENT"))
            .body("reasonNote", equalTo(reasonNote));
    }

    @Test
    @Order(4)
    @DisplayName("AC2: Reason note visible in flagged accounts dashboard summary")
    void test_reason_note_visible_in_dashboard_account_summary() {
        Response response = given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
        .when()
            .get("/advisor/dashboard/flagged")
        .then()
            .statusCode(200)
            .body("$", not(empty()))
            .body("collect { it.clientId }", hasItem(CLIENT_ID))
            .extract().response();

        String reasonNote = response.jsonPath().getString(
            "find { it.clientId == '" + CLIENT_ID + "' }.reasonNote"
        );
        assertNotNull(reasonNote, "reasonNote must be visible in the account summary entry");
    }

    @Test
    @Order(5)
    @DisplayName("AC3: Remove flag from account returns 200 with flagged=false")
    void test_unflag_client_account_returns_200_with_flagged_false() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("flagged", false);
        requestBody.put("reason", "PORTFOLIO_CONCERN");

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .put("/clients/" + CLIENT_ID + "/flag")
        .then()
            .statusCode(200)
            .body("clientId", equalTo(CLIENT_ID))
            .body("flagged", equalTo(false));
    }

    @Test
    @Order(6)
    @DisplayName("AC3: Unflagged account no longer appears in advisor flagged dashboard")
    void test_unflagged_account_absent_from_dashboard() {
        Response response = given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
        .when()
            .get("/advisor/dashboard/flagged")
        .then()
            .statusCode(200)
            .extract().response();

        java.util.List<String> flaggedClientIds = response.jsonPath().getList("clientId");
        if (flaggedClientIds != null) {
            assertFalse(
                flaggedClientIds.contains(CLIENT_ID),
                "Unflagged account should not appear in the flagged dashboard"
            );
        }
    }

    @Test
    @Order(7)
    @DisplayName("Negative: Flag account with missing required fields returns 400")
    void test_flag_account_fails_when_required_fields_missing() {
        Map<String, Object> incompleteBody = new HashMap<>();

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(incompleteBody)
        .when()
            .put("/clients/" + CLIENT_ID + "/flag")
        .then()
            .statusCode(400);
    }

    @Test
    @Order(8)
    @DisplayName("Negative: Flag account without auth token returns 401")
    void test_flag_account_returns_401_without_token() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("flagged", true);
        requestBody.put("reason", "COMPLIANCE");

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer ")
            .body(requestBody)
        .when()
            .put("/clients/" + CLIENT_ID + "/flag")
        .then()
            .statusCode(401);
    }

    @Test
    @Order(9)
    @DisplayName("Negative: Flag account with invalid reason enum returns 422")
    void test_flag_account_returns_422_with_invalid_reason_enum() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("flagged", true);
        requestBody.put("reason", "INVALID_REASON_VALUE");

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .put("/clients/" + CLIENT_ID + "/flag")
        .then()
            .statusCode(422);
    }

    @Test
    @Order(10)
    @DisplayName("Negative: Flag non-existent client returns 404")
    void test_flag_account_returns_404_when_client_not_exists() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("flagged", true);
        requestBody.put("reason", "OTHER");

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .body(requestBody)
        .when()
            .put("/clients/" + NON_EXISTENT_CLIENT_ID + "/flag")
        .then()
            .statusCode(404);
    }

    @Test
    @Order(11)
    @DisplayName("Negative: Flag account as non-advisor role returns 403")
    void test_flag_account_returns_403_for_non_advisor_role() {
        String clientRoleToken = System.getProperty("api.client.role.token", "client-role-jwt-token");
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("flagged", true);
        requestBody.put("reason", "PORTFOLIO_CONCERN");

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + clientRoleToken)
            .body(requestBody)
        .when()
            .put("/clients/" + CLIENT_ID + "/flag")
        .then()
            .statusCode(403);
    }
}
