package com.elitea.tests.investments;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Automated API tests for MAP-66 — Recurring Automatic Investments
 * Jira Story: https://duggisrinivasarao.atlassian.net/browse/MAP-66
 * Related:    https://duggisrinivasarao.atlassian.net/browse/MAP-48
 * Generated by: Claude (Elitea Test Automation Pipeline)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RecurringInvestmentsTest {

    private static final String BASE_URL = System.getProperty("api.base.url", "https://api.elitea.ai");
    private static final String AUTH_TOKEN = System.getProperty("api.auth.token", "");
    private static String createdScheduleId;

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test @Order(1)
    @DisplayName("AC1 — Create recurring investment with valid payload returns 201")
    void test_recurring_investment_create_returns_201_with_valid_payload() {
        Map<String, Object> body = new HashMap<>();
        body.put("amount", 500.00); body.put("frequency", "MONTHLY");
        body.put("targetFundId", "FUND-001"); body.put("startDate", "2026-05-01");
        Response response = given().contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN).body(body)
            .when().post("/api/investments/recurring")
            .then().statusCode(201).body("id", notNullValue())
            .body("status", equalTo("ACTIVE")).body("confirmed", equalTo(true))
            .extract().response();
        createdScheduleId = response.jsonPath().getString("id");
    }

    @Test @Order(2)
    @DisplayName("AC1 — Create recurring investment missing amount returns 400")
    void test_recurring_investment_create_fails_when_amount_missing() {
        Map<String, Object> body = new HashMap<>();
        body.put("frequency", "MONTHLY"); body.put("targetFundId", "FUND-001"); body.put("startDate", "2026-05-01");
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN).body(body)
            .when().post("/api/investments/recurring")
            .then().statusCode(400).body("errorCode", equalTo("MISSING_REQUIRED_FIELD")).body("field", equalTo("amount"));
    }

    @Test @Order(3)
    @DisplayName("AC1 — Create recurring investment missing frequency returns 400")
    void test_recurring_investment_create_fails_when_frequency_missing() {
        Map<String, Object> body = new HashMap<>();
        body.put("amount", 500.00); body.put("targetFundId", "FUND-001"); body.put("startDate", "2026-05-01");
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN).body(body)
            .when().post("/api/investments/recurring")
            .then().statusCode(400).body("errorCode", equalTo("MISSING_REQUIRED_FIELD")).body("field", equalTo("frequency"));
    }

    @Test @Order(4)
    @DisplayName("AC1 — Create recurring investment with invalid fund returns 422")
    void test_recurring_investment_create_fails_when_fund_invalid() {
        Map<String, Object> body = new HashMap<>();
        body.put("amount", 500.00); body.put("frequency", "MONTHLY");
        body.put("targetFundId", "NONEXISTENT-FUND"); body.put("startDate", "2026-05-01");
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN).body(body)
            .when().post("/api/investments/recurring")
            .then().statusCode(422).body("errorCode", equalTo("INVALID_FUND")).body("field", equalTo("targetFundId"));
    }

    @Test @Order(5)
    @DisplayName("AC1 — Get existing recurring investment returns 200 with schedule details")
    void test_recurring_investment_get_returns_200_with_schedule_details() {
        Assumptions.assumeTrue(createdScheduleId != null);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN)
            .when().get("/api/investments/recurring/" + createdScheduleId)
            .then().statusCode(200).body("id", equalTo(createdScheduleId)).body("status", equalTo("ACTIVE"));
    }

    @Test @Order(6)
    @DisplayName("AC1 — Get non-existent recurring investment returns 404")
    void test_recurring_investment_get_returns_404_when_not_exists() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN)
            .when().get("/api/investments/recurring/INVALID-99999")
            .then().statusCode(404).body("errorCode", equalTo("SCHEDULE_NOT_FOUND"));
    }

    @Test @Order(7)
    @DisplayName("AC1 — Update recurring investment amount and frequency returns 200")
    void test_recurring_investment_update_returns_200_with_updated_fields() {
        Assumptions.assumeTrue(createdScheduleId != null);
        Map<String, Object> body = new HashMap<>();
        body.put("amount", 750.00); body.put("frequency", "WEEKLY");
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN).body(body)
            .when().put("/api/investments/recurring/" + createdScheduleId)
            .then().statusCode(200).body("amount", equalTo(750.00f)).body("frequency", equalTo("WEEKLY"));
    }

    @Test @Order(8)
    @DisplayName("AC2 — Execute investment with sufficient funds returns EXECUTED status")
    void test_recurring_investment_execute_returns_200_when_funds_sufficient() {
        Assumptions.assumeTrue(createdScheduleId != null);
        Map<String, Object> body = new HashMap<>();
        body.put("scheduleId", createdScheduleId); body.put("triggerDate", "2026-05-01"); body.put("availableBalance", 5000.00);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN).body(body)
            .when().post("/api/investments/recurring/" + createdScheduleId + "/execute")
            .then().statusCode(200).body("status", equalTo("EXECUTED")).body("transactionId", notNullValue());
    }

    @Test @Order(9)
    @DisplayName("AC2 — Executed investment is recorded in execution history")
    void test_recurring_investment_execution_recorded_in_transaction_history() {
        Assumptions.assumeTrue(createdScheduleId != null);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN)
            .when().get("/api/investments/recurring/" + createdScheduleId + "/history")
            .then().statusCode(200).body("executions", hasSize(greaterThanOrEqualTo(1)))
            .body("executions[0].status", equalTo("EXECUTED"));
    }

    @Test @Order(10)
    @DisplayName("AC3 — Execute investment with insufficient funds returns FAILED status and notificationSent=true")
    void test_recurring_investment_execute_fails_when_funds_insufficient() {
        Assumptions.assumeTrue(createdScheduleId != null);
        Map<String, Object> body = new HashMap<>();
        body.put("scheduleId", createdScheduleId); body.put("triggerDate", "2026-06-01"); body.put("availableBalance", 10.00);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN).body(body)
            .when().post("/api/investments/recurring/" + createdScheduleId + "/execute")
            .then().statusCode(200).body("status", equalTo("FAILED"))
            .body("failureReason", equalTo("INSUFFICIENT_FUNDS")).body("notificationSent", equalTo(true));
    }

    @Test @Order(11)
    @DisplayName("AC3 — Notification is created when investment fails due to insufficient funds")
    void test_notification_created_when_investment_fails_due_to_insufficient_funds() {
        Assumptions.assumeTrue(createdScheduleId != null);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN)
            .when().get("/api/notifications?scheduleId=" + createdScheduleId + "&type=INSUFFICIENT_FUNDS")
            .then().statusCode(200).body("notifications", hasSize(greaterThanOrEqualTo(1)))
            .body("notifications[0].type", equalTo("INSUFFICIENT_FUNDS"))
            .body("notifications[0].message", containsString("funds"));
    }

    @Test @Order(12)
    @DisplayName("Auth — Create investment without token returns 401")
    void test_recurring_investment_create_returns_401_without_token() {
        Map<String, Object> body = new HashMap<>();
        body.put("amount", 500.00); body.put("frequency", "MONTHLY"); body.put("targetFundId", "FUND-001");
        given().contentType(ContentType.JSON).header("Authorization", "Bearer ").body(body)
            .when().post("/api/investments/recurring")
            .then().statusCode(401).body("errorCode", equalTo("UNAUTHORIZED"));
    }

    @Test @Order(13)
    @DisplayName("Auth — Get investment without token returns 401")
    void test_recurring_investment_get_returns_401_without_token() {
        given().contentType(ContentType.JSON).header("Authorization", "Bearer ")
            .when().get("/api/investments/recurring/some-id")
            .then().statusCode(401).body("errorCode", equalTo("UNAUTHORIZED"));
    }

    @Test @Order(14)
    @DisplayName("Cleanup — Cancel recurring investment returns 204")
    void test_recurring_investment_delete_returns_204() {
        Assumptions.assumeTrue(createdScheduleId != null);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN)
            .when().delete("/api/investments/recurring/" + createdScheduleId)
            .then().statusCode(204);
    }

    @Test @Order(15)
    @DisplayName("Cleanup — Cancelled investment returns 404 on retrieval")
    void test_recurring_investment_get_returns_404_after_cancellation() {
        Assumptions.assumeTrue(createdScheduleId != null);
        given().contentType(ContentType.JSON).header("Authorization", "Bearer " + AUTH_TOKEN)
            .when().get("/api/investments/recurring/" + createdScheduleId)
            .then().statusCode(404).body("errorCode", equalTo("SCHEDULE_NOT_FOUND"));
    }
}
