package com.elitea.tests.retirement;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Automated API tests for MAP-18 — Retirement Savings Calculator
 * Story: As a client, I want to input my target retirement age and income needs,
 *        so that the system can calculate how much I need to save.
 * Epic:  MAP-5 — Retirement Planning Tools
 * Confluence spec: https://duggisrinivasarao.atlassian.net/wiki/spaces/~557058465a0e4979f9409ab37f2f57376baf82/pages/11731021/MAP-18+Retirement+Savings+Calculator
 * Generated by: Claude (Elitea Test Automation Pipeline)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RetirementCalculatorTest {

    private static final String BASE_URL = System.getProperty(
            "api.base.url", "https://api.edwardjones-map.com"
    );
    private static final String CLIENT_TOKEN = System.getProperty(
            "api.client.auth.token", ""
    );
    private static final String ADVISOR_TOKEN = System.getProperty(
            "api.advisor.auth.token", ""
    );
    private static final String CALCULATOR_ENDPOINT = "/retirement/calculator";
    private static final String RESULTS_ENDPOINT = "/clients/{clientId}/retirement/calculator/results";
    private static final String VALID_CLIENT_ID = System.getProperty(
            "api.test.client.id", "test-client-uuid-001"
    );

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    @Order(1)
    @DisplayName("AC1 TC-01: POST calculator with valid inputs returns 200 with savings target")
    void test_calculator_post_returns_200_with_valid_inputs() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30);
        requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00);
        requestBody.put("monthlyContribution", 1000.00);
        requestBody.put("expectedAnnualReturn", 7.0);

        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + CLIENT_TOKEN)
            .body(requestBody)
        .when()
            .post(CALCULATOR_ENDPOINT)
        .then()
            .statusCode(200)
            .body("projectedRetirementBalance", notNullValue())
            .body("requiredMonthlySavings", notNullValue())
            .body("savingsGap", notNullValue())
            .body("assumptionsSummary", notNullValue())
            .body("assumptionsSummary.yearsToRetirement", equalTo(35))
            .body("assumptionsSummary.returnRate", equalTo(7.0f));
    }

    // ... (all 20 test methods as generated)
}
