package com.elitea.tests.retirement;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Automated API tests for MAP-18 — Retirement Savings Calculator
 * Story: As a client, I want to input my target retirement age and income needs,
 *        so that the system can calculate how much I need to save.
 * Confluence spec: https://duggisrinivasarao.atlassian.net/wiki/spaces/.../pages/17367043
 * Jira: https://duggisrinivasarao.atlassian.net/browse/MAP-18
 * Generated by: Claude (Elitea Test Automation Pipeline)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RetirementCalculatorTest {

    private static final String BASE_URL = System.getProperty("api.base.url", "https://api.edwardjones-map.com");
    private static final String CLIENT_TOKEN = System.getProperty("api.client.auth.token", "");
    private static final String ADVISOR_TOKEN = System.getProperty("api.advisor.auth.token", "");
    private static final String TEST_CLIENT_ID = System.getProperty("api.test.client.id", "client-test-001");

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    // AC1 Happy Path Tests (TC01-TC03)
    @Test @Order(1) @DisplayName("AC1-TC01: Valid inputs return 200 with all response fields")
    void test_retirementCalculator_validInputs_returns200_withAllResponseFields() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00); requestBody.put("monthlyContribution", 1000.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator")
        .then().statusCode(200).body("projectedRetirementBalance",notNullValue()).body("requiredMonthlySavings",notNullValue()).body("savingsGap",notNullValue()).body("assumptionsSummary",notNullValue());
    }

    @Test @Order(2) @DisplayName("AC1-TC02: Zero current savings returns 200")
    void test_retirementCalculator_zeroCurrentSavings_returns200() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 25); requestBody.put("targetRetirementAge", 60);
        requestBody.put("currentSavings", 0.00); requestBody.put("monthlyContribution", 500.00);
        requestBody.put("expectedAnnualReturn", 6.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator")
        .then().statusCode(200).body("projectedRetirementBalance",notNullValue());
    }

    @Test @Order(3) @DisplayName("AC1-TC03: Zero monthly contribution returns 200, savingsGap reflects full deficit")
    void test_retirementCalculator_zeroMonthlyContribution_savingsGapReflectsFullDeficit() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 40); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 10000.00); requestBody.put("monthlyContribution", 0.00);
        requestBody.put("expectedAnnualReturn", 5.0);
        Response response = given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator")
        .then().statusCode(200).extract().response();
        assertTrue(response.jsonPath().getFloat("savingsGap") > 0);
    }

    // AC2 Output Validation Tests (TC04-TC07)
    @Test @Order(4) @DisplayName("AC2-TC04: assumptionsSummary contains yearsToRetirement, inflationAssumption, returnRate")
    void test_retirementCalculator_response_containsAssumptionsSummaryFields() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 35); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 75000.00); requestBody.put("monthlyContribution", 1500.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator")
        .then().statusCode(200).body("assumptionsSummary.yearsToRetirement",equalTo(30)).body("assumptionsSummary.returnRate",equalTo(7.0f));
    }

    @Test @Order(5) @DisplayName("AC2-TC05: Conservative return rate 4% returns 200")
    void test_retirementCalculator_conservativeReturnRate_returns200() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00); requestBody.put("monthlyContribution", 1000.00);
        requestBody.put("expectedAnnualReturn", 4.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator")
        .then().statusCode(200).body("assumptionsSummary.returnRate",equalTo(4.0f));
    }

    @Test @Order(6) @DisplayName("AC2-TC06: Aggressive return rate 10% returns 200")
    void test_retirementCalculator_aggressiveReturnRate_returns200() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00); requestBody.put("monthlyContribution", 1000.00);
        requestBody.put("expectedAnnualReturn", 10.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator")
        .then().statusCode(200).body("assumptionsSummary.returnRate",equalTo(10.0f));
    }

    @Test @Order(7) @DisplayName("AC2-TC07: requiredMonthlySavings > 0 when savingsGap is positive")
    void test_retirementCalculator_requiredMonthlySavingsPositive_whenSavingsGapExists() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 45); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 5000.00); requestBody.put("monthlyContribution", 200.00);
        requestBody.put("expectedAnnualReturn", 5.0);
        Response response = given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(200).extract().response();
        float gap = response.jsonPath().getFloat("savingsGap");
        if (gap > 0) assertTrue(response.jsonPath().getFloat("requiredMonthlySavings") > 0);
    }

    // AC3 Validation / Error Handling Tests (TC08-TC13)
    @Test @Order(8) @DisplayName("AC3-TC08: targetRetirementAge equals currentAge returns 422")
    void test_retirementCalculator_fails_when_targetRetirementAge_equalsCurrentAge() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 40); requestBody.put("targetRetirementAge", 40);
        requestBody.put("currentSavings", 20000.00); requestBody.put("monthlyContribution", 500.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(422);
    }

    @Test @Order(9) @DisplayName("AC3-TC09: targetRetirementAge less than currentAge returns 422")
    void test_retirementCalculator_fails_when_targetRetirementAge_lessThanCurrentAge() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 50); requestBody.put("targetRetirementAge", 40);
        requestBody.put("currentSavings", 20000.00); requestBody.put("monthlyContribution", 500.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(422);
    }

    @Test @Order(10) @DisplayName("AC3-TC10: Negative currentSavings returns 422")
    void test_retirementCalculator_fails_when_currentSavings_isNegative() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", -1.00); requestBody.put("monthlyContribution", 500.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(422);
    }

    @Test @Order(11) @DisplayName("AC3-TC11: Missing currentAge returns 400")
    void test_retirementCalculator_returns400_when_currentAge_isMissing() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("targetRetirementAge", 65); requestBody.put("currentSavings", 50000.00);
        requestBody.put("monthlyContribution", 1000.00); requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(400);
    }

    @Test @Order(12) @DisplayName("AC3-TC12: Missing targetRetirementAge returns 400")
    void test_retirementCalculator_returns400_when_targetRetirementAge_isMissing() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("currentSavings", 50000.00);
        requestBody.put("monthlyContribution", 1000.00); requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(400);
    }

    @Test @Order(13) @DisplayName("AC3-TC13: Missing expectedAnnualReturn returns 400")
    void test_retirementCalculator_returns400_when_expectedAnnualReturn_isMissing() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00); requestBody.put("monthlyContribution", 1000.00);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(400);
    }

    // Auth & Security Tests (TC14-TC16)
    @Test @Order(14) @DisplayName("AUTH-TC14: POST without Authorization header returns 401")
    void test_retirementCalculator_returns401_withoutAuthorizationHeader() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00); requestBody.put("monthlyContribution", 1000.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(401);
    }

    @Test @Order(15) @DisplayName("AUTH-TC15: POST with invalid JWT returns 401")
    void test_retirementCalculator_returns401_withInvalidToken() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00); requestBody.put("monthlyContribution", 1000.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer invalid.token.here").body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(401);
    }

    @Test @Order(16) @DisplayName("AUTH-TC16: ADVISOR role calling POST returns 403")
    void test_retirementCalculator_returns403_whenAdvisorRoleCallsPost() {
        Map<String, Object> requestBody = new HashMap<>();
        requestBody.put("currentAge", 30); requestBody.put("targetRetirementAge", 65);
        requestBody.put("currentSavings", 50000.00); requestBody.put("monthlyContribution", 1000.00);
        requestBody.put("expectedAnnualReturn", 7.0);
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+ADVISOR_TOKEN).body(requestBody)
        .when().post("/retirement/calculator").then().statusCode(403);
    }

    // GET Advisor Endpoint Tests (TC17-TC20)
    @Test @Order(17) @DisplayName("GET-TC17: Valid ADVISOR token + existing clientId returns 200")
    void test_retirementResults_advisorToken_validClientId_returns200() {
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+ADVISOR_TOKEN)
        .when().get("/clients/"+TEST_CLIENT_ID+"/retirement/calculator/results")
        .then().statusCode(200).body("projectedRetirementBalance",notNullValue());
    }

    @Test @Order(18) @DisplayName("GET-TC18: Non-existent clientId returns 404")
    void test_retirementResults_returns404_whenClientIdDoesNotExist() {
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+ADVISOR_TOKEN)
        .when().get("/clients/nonexistent-client-99999/retirement/calculator/results")
        .then().statusCode(404);
    }

    @Test @Order(19) @DisplayName("GET-TC19: GET results without auth returns 401")
    void test_retirementResults_returns401_withoutAuthorizationHeader() {
        given().contentType(ContentType.JSON)
        .when().get("/clients/"+TEST_CLIENT_ID+"/retirement/calculator/results")
        .then().statusCode(401);
    }

    @Test @Order(20) @DisplayName("GET-TC20: CLIENT role calling GET results returns 403")
    void test_retirementResults_returns403_whenClientRoleCallsGetResults() {
        given().contentType(ContentType.JSON).header("Authorization","Bearer "+CLIENT_TOKEN)
        .when().get("/clients/"+TEST_CLIENT_ID+"/retirement/calculator/results")
        .then().statusCode(403);
    }
}
