package com.elitea.tests.portfolio;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.*;

import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Automated API tests for MAP-13 — Real-Time Portfolio Dashboard
 * Story: As a client, I want to view a real-time dashboard of my portfolio
 *        holdings, so that I can monitor my investments at a glance.
 * Confluence spec: https://duggisrinivasarao.atlassian.net/wiki/spaces/.../pages/11730976
 * Generated by: Claude (Elitea Test Automation Pipeline)
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class MAP13PortfolioDashboardTest {

    private static final String BASE_URL = System.getProperty(
        "api.base.url", "https://api.edwardjones-map.com"
    );
    private static final String AUTH_TOKEN = System.getProperty(
        "api.auth.token", ""
    );
    private static final String CLIENT_ID = System.getProperty(
        "test.client.id", "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    );
    private static final String INVALID_CLIENT_ID = "non-existent-client-99999";
    private static final String MALFORMED_CLIENT_ID = "not-a-uuid!!!";
    private static final String ADVISOR_TOKEN = System.getProperty(
        "api.advisor.auth.token", ""
    );

    @BeforeAll
    static void setup() {
        RestAssured.baseURI = BASE_URL;
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    @Order(1)
    @DisplayName("AC1 [TC-01]: Valid clientId returns portfolio summary with HTTP 200")
    void test_portfolio_summary_returns_200_for_valid_client() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(200)
            .contentType(ContentType.JSON);
    }

    @Test
    @Order(2)
    @DisplayName("AC1 [TC-02]: Portfolio summary response contains required fields")
    void test_portfolio_summary_response_contains_required_fields() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(200)
            .body("totalPortfolioValue", notNullValue())
            .body("totalPortfolioValue", instanceOf(Number.class))
            .body("dailyChange", notNullValue())
            .body("dailyChangePct", notNullValue())
            .body("holdings", notNullValue())
            .body("holdings", isA(java.util.List.class));
    }

    @Test
    @Order(3)
    @DisplayName("AC1 [TC-03]: Each holding contains all required fields with real-time price data")
    void test_portfolio_holdings_contain_required_fields() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}/holdings")
        .then()
            .statusCode(200)
            .body("holdings", not(empty()))
            .body("holdings[0].ticker", notNullValue())
            .body("holdings[0].name", notNullValue())
            .body("holdings[0].quantity", notNullValue())
            .body("holdings[0].currentPrice", notNullValue())
            .body("holdings[0].marketValue", notNullValue())
            .body("holdings[0].gainLoss", notNullValue())
            .body("holdings[0].gainLossPct", notNullValue());
    }

    @Test
    @Order(4)
    @DisplayName("AC1 [TC-04]: Holdings list includes all asset classes — stocks, bonds, mutual funds, ETFs")
    void test_portfolio_holdings_covers_all_asset_classes() {
        Response response = given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}/holdings")
        .then()
            .statusCode(200)
            .extract().response();

        java.util.List<String> assetClasses = response.jsonPath().getList("holdings.assetClass");
        assertNotNull(assetClasses, "holdings.assetClass list should not be null");
        assertTrue(
            assetClasses.contains("STOCKS") ||
            assetClasses.contains("BONDS") ||
            assetClasses.contains("MUTUAL_FUNDS") ||
            assetClasses.contains("ETFS"),
            "Expected at least one recognised asset class in holdings"
        );
    }

    @Test
    @Order(5)
    @DisplayName("AC2 [TC-05]: Total portfolio value and daily gain/loss are numeric and present")
    void test_portfolio_total_value_and_daily_gain_loss_are_numeric() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(200)
            .body("totalPortfolioValue", greaterThanOrEqualTo(0.0f))
            .body("dailyChange", notNullValue())
            .body("dailyChangePct", notNullValue());
    }

    @Test
    @Order(6)
    @DisplayName("AC2 [TC-06]: Market data outage flag is absent when market data is available")
    void test_portfolio_has_no_outage_flag_when_market_data_available() {
        Response response = given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(200)
            .extract().response();

        Boolean outageNotice = response.jsonPath().get("outageNotice");
        if (outageNotice != null) {
            assertFalse(outageNotice, "outageNotice should be false when market data is available");
        }
    }

    @Test
    @Order(7)
    @DisplayName("AC3 [TC-07]: Market data outage — response contains outageNotice flag and lastUpdated timestamp")
    void test_portfolio_outage_response_contains_outage_notice_and_timestamp() {
        Response response = given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .header("X-Simulate-Market-Outage", "true")
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(200)
            .body("outageNotice", equalTo(true))
            .body("lastUpdated", notNullValue())
            .body("totalPortfolioValue", notNullValue())
            .body("holdings", notNullValue())
            .extract().response();

        String lastUpdated = response.jsonPath().getString("lastUpdated");
        assertNotNull(lastUpdated, "lastUpdated timestamp must be present during outage");
        assertFalse(lastUpdated.isEmpty(), "lastUpdated timestamp must not be empty");
    }

    @Test
    @Order(8)
    @DisplayName("AC3 [TC-08]: Portfolio with zero holdings returns empty array, not null")
    void test_portfolio_with_zero_holdings_returns_empty_array() {
        String emptyPortfolioClientId = System.getProperty(
            "test.empty.portfolio.client.id", "00000000-0000-0000-0000-000000000001"
        );
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", emptyPortfolioClientId)
        .when()
            .get("/portfolio/{clientId}/holdings")
        .then()
            .statusCode(200)
            .body("holdings", notNullValue())
            .body("holdings", hasSize(0));
    }

    @Test
    @Order(9)
    @DisplayName("TC-09: Missing Authorization header returns 401 Unauthorized")
    void test_portfolio_returns_401_without_auth_header() {
        given()
            .contentType(ContentType.JSON)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(401);
    }

    @Test
    @Order(10)
    @DisplayName("TC-10: Invalid/expired JWT token returns 401 Unauthorized")
    void test_portfolio_returns_401_with_invalid_token() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer invalid.jwt.token.here")
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(401);
    }

    @Test
    @Order(11)
    @DisplayName("TC-11: ADVISOR role JWT on CLIENT-only endpoint returns 403 Forbidden")
    void test_portfolio_returns_403_when_advisor_accesses_client_endpoint() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + ADVISOR_TOKEN)
            .pathParam("clientId", CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(403);
    }

    @Test
    @Order(12)
    @DisplayName("TC-12: Non-existent clientId returns 404 Not Found")
    void test_portfolio_returns_404_for_non_existent_client() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", INVALID_CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(404);
    }

    @Test
    @Order(13)
    @DisplayName("TC-13: Malformed clientId (non-UUID) returns 400 Bad Request")
    void test_portfolio_returns_400_for_malformed_client_id() {
        given()
            .contentType(ContentType.JSON)
            .header("Authorization", "Bearer " + AUTH_TOKEN)
            .pathParam("clientId", MALFORMED_CLIENT_ID)
        .when()
            .get("/portfolio/{clientId}")
        .then()
            .statusCode(400);
    }
}
